### ISSUE TITLE
Better navigation

### ISSUE THREAD

**Issue by just1689** [jcuenod/lafwebpy#1]
That is all

**Comment by jcuenod** [comment]
lol - when did you last try it?
I have made some dramatic improvements to navigation since the beginning...

**Comment by jcuenod** [comment]
i.e. have you tried it since https://github.com/jcuenod/lafwebpy/commit/c4da426f377fe37371475352595e94698809b3b3

**Comment by jcuenod** [comment]
Well I'm going to close this because I've switched over to react. The nav has changed but not by much to be honest (it does remember where you were though).
